---
name: Test

"on":
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          ln -s doesnt-exist broken
      - run: |
          echo ${{ hashFiles('*') }}
